spring:
  application:
    name: agenda
  datasource:
    url: jdbc:mysql://localhost:3306/app_agenda?userSSl=false
    username: root
    password: 'lc57910p'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect